FROM python:3.11-slim
RUN apt-get update && apt-get upgrade -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
# hadolint ignore=DL3013
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir paho-mqtt==1.6.1
COPY mqtt_watcher.py .
USER nobody
CMD ["python", "-u", "mqtt_watcher.py"]
